### ISSUE TITLE
No backslash worries in Windows 10

### ISSUE THREAD

**Issue by komwomak** [b-rodrigues/modern_R#3]
https://github.com/b-rodrigues/modern_R/blob/2a7bf9b4664db2c80c92ea266ea42c45545472fb/03-reading_writing_data.Rmd#L36

Windows 10 RStudio seems to work just fine with UNIX-style forward slashes (/////) in file and setwd() references.  It SEEMS to interpret \ as the UNIX-style escape  character.

gitbash yields a terminal window for Windows 10 that understands UNIX commands ls, ln, vi, cd, mv, cp, mkdir...  With / as understood in UNIX.

**Comment by b-rodrigues** [comment]
yep, "/" works on Rstudio on Windows too. But the paths on Windows use backslashes, so if you're copy pasting a path from the windows explorer in Rstudio you'll need to change the backslahes to forwardslahes.
